{{ if not .Namespace }}
{"\n\nIt is mandatory to pass the namespace to helmfile:\nhelmfile -n app [-e sidecar]\n\n": "" }
{{ end }}
---
repositories:
- name: bento
  url: https://warpstreamlabs.github.io/bento-helm-chart

---
environments:
  default:
    values:
      - ollama_sidecar: false
      - ollama_api_endpoint: http://ollama:11434/api/generate
  sidecar:
    values:
      - ollama_sidecar: true
      - ollama_api_endpoint: http://localhost:11434/api/generate
---

# Build the AMQP connection URL used in producer and consumer
{{- $username := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/username" .Namespace) }}
{{- $password := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/password" .Namespace) }}
{{- $host     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/host"     .Namespace) }}
{{- $port     := fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/mq-default-user/port"     .Namespace) }}
{{- $amqpurl  := printf "amqp://%s:%s@%s:%s/" $username $password $host $port }}

releases:

- name: bento-generator
  chart: bento/bento
  version: 0.1.0
  values:
    - ./values-bento-generator.yml
    - extraVolumes:
        - name: data
    - extraVolumeMounts:
        - name: data
          mountPath: /data
    - initContainers:
        - name: fetchdata
          image: nixery.dev/shell/curl/jq
          command:
          - sh
          - -c
          - |
            curl -fsSL https://gitlab.com/xavki/tutoriels-python/-/raw/master/cities.json | jq -c .[] > /data/cities.jsonl
          volumeMounts:
            - name: data
              mountPath: /data

- name: bento-api
  chart: bento/bento
  version: 0.1.0
  values: [ ./values-bento-api.yml ]
  set:
  - name: config.output.amqp_0_9.urls[0]
    value: {{ $amqpurl }}

- name: bento-consumer
  chart: bento/bento
  version: 0.1.0
  values: [ ./values-bento-consumer.yml ]
  set:
  - name: config.output.sql_insert.dsn
    value: {{ fetchSecretValue (printf "secretref+k8s://v1/Secret/%s/db-app/uri" .Namespace) }}
  - name: config.input.amqp_0_9.urls[0]
    value: {{ $amqpurl }}
  - name: config.pipeline.processors[0].branch.processors[0].http.url
    value: {{ .Environment.Values.ollama_api_endpoint }}
  {{ if .Environment.Values.ollama_sidecar }}
  strategicMergePatches:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bento-consumer
      spec:
        template:
          spec:
            volumes:
            - name: ollama
              hostPath:
                path: /opt/ollama
                type: DirectoryOrCreate
            containers:
            - image: ollama/ollama
              name: ollama
              env:
              - name: OLLAMA_MAX_QUEUE
                valueFrom:
                  configMapKeyRef:
                    name: ollama
                    key: queue
              volumeMounts:
              - name: ollama
                mountPath: /root/.ollama
              readinessProbe:
                httpGet:
                  port: 11434
              resources:
                requests:
                  cpu: 3
                limits:
                  cpu: 6
            - image: alpine/httpie
              name: pull-model
              resources:
                requests:
                  cpu: 0.01
                limits:
                  cpu: 1
              env:
              - name: MODEL
                valueFrom:
                  configMapKeyRef:
                    name: ollama
                    key: model
              command:
              - sh
              - -c
              - |
                set -e
                echo -n $(MODEL) > /model
                http -I --check-status http://localhost:11434/api/pull name=@/model
                exec sleep infinity
              readinessProbe:
                # We don't need to hit the API endpoint every 10 seconds.
                # However, we increase the timeout, because ollama sometimes
                # takes a couple of seconds to reply, which causes the probe
                # to fail (the default timeout is 1 second).
                periodSeconds: 60
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 1
                exec:
                  command:
                  - http
                  - -I
                  - --check-status
                  # Use "show" to just check if model has been pulled successfully.
                  #- name=@/model
                  #- http://localhost:11434/api/show
                  # Or use "generate" with an empty payload to force ollama to keep the model loaded in RAM.
                  - http://localhost:11434/api/generate
                  - model=@/model
  {{ end }}

{{ if .Environment.Values.ollama_sidecar }}
- name: keda-autoscaler
  chart: ./keda
  strategicMergePatches:
    - apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      metadata:
        name: bento-consumer
        namespace: {{ .Namespace }}
      spec:
        pollingInterval: 30
        cooldownPeriod: 10
        minReplicaCount: 0 
        maxReplicaCount: 100 
        triggers:
          - type: rabbitmq
            metadata:
              protocol: auto
              queueName: q1
              mode: QueueLength # QueueLength or MessageRate
              value: "10"
              host: {{ $amqpurl }}
{{ end }}
