#commonLabels:
#  release: promstack
config:
  input:
    http_server:
      #path: "/post" # default value
      allowed_verbs:
        - POST
    processors:
      - log:
          level: INFO
          fields_mapping: "root = this"
  pipeline:
    processors:
      - switch:
        - check: '@http_server_request_path == "/post"'
          processors:
            - mapping: |
                root.submitted_at = now()
                root.city = this.city
                root.prompt = "If you go to " + root.city + ", I suggest that you"
                root.uuid = uuid_v4()
            # to debug headers
            #- log:
            #    level: INFO
            #    message: "${! meta() }"
  output:
    amqp_0_9:
      #urls: 
      #  - amqp://enix:password@mq:5672/
      exchange: "ex1"
      key: "rkey"
      max_in_flight: 100000

resources: 
  limits:
    cpu: 1
    memory: 1G
  requests:
    cpu: 0.1
    memory: 1G

metrics:
  prometheus:
    add_process_metrics: true
    add_go_metrics: true
serviceMonitor:
  enabled: true 
