apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
spec:
  ports:
  - name: "11434"
    port: 11434
    protocol: TCP
    targetPort: haproxy
  selector:
    app: ollama
  type: ClusterIP
